apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-backend
  namespace: student-registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-backend
  template:
    metadata:
      labels:
        app: student-backend
    spec:
      containers:
        - name: backend
          image: my56k8s.jfrog.io/sample-docker-local/student-registration-backend:latest
          imagePullPolicy: Always   # 🔥 ensures latest image is pulled
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: mysql-root-password
            - name: DB_NAME
              value: student_registration
            - name: PORT
              value: "5000"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"