apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-frontend
  namespace: student-registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-frontend
  template:
    metadata:
      labels:
        app: student-frontend
    spec:
      containers:
        - name: frontend
          image: my56k8s.jfrog.io/sample-docker-local/student-registration-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "http://student-backend:5000/api"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"