apiVersion: v1
kind: Service
metadata:
  name: student-frontend
  namespace: student-registration
spec:
  selector:
    app: student-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: NodePort
  nodePort: 30080
