apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: student-registration
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: mysql
  type: ClusterIP
